//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVDWPF.AppData
{
    using SVDWPF.Pages;
    using System;
    using System.Collections.Generic;
    
    public partial class Ychetn
    {
       
        public int nomer_zapisi { get; set; }
        public Nullable<int> nomer_licevogo_Scheta { get; set; }
        public string Mesyac { get; set; }
        public string Tariff { get; set; }
        public Nullable<int> kolvo_kilovatt { get; set; }
    
        public virtual Spravoch Spravoch { get; set; }
    }
}
